quarkus.application.name=compas-validation-service

quarkus.http.port=8080
quarkus.http.body.handle-file-uploads=true
quarkus.http.limits.max-body-size=600M
quarkus.resteasy.multipart.max-file-size=500M

quarkus.http.cors.enabled=true
quarkus.http.cors.origins = *
quarkus.http.cors.methods = POST

quarkus.http.auth.proactive=true

smallrye.jwt.verify.key.location = ${JWT_VERIFY_KEY:http://localhost:8089/auth/realms/compas/protocol/openid-connect/certs}
mp.jwt.verify.issuer             = ${JWT_VERIFY_ISSUER:http://localhost:8089/auth/realms/compas}
mp.jwt.verify.audiences          = ${JWT_VERIFY_CLIENT_ID:validation-service}
smallrye.jwt.path.groups         = ${JWT_GROUPS_PATH:resource_access/validation-service/roles}

quarkus.http.auth.permission.allow-quarkus-services.paths=/q/health/live,/q/health/ready,/q/openapi
quarkus.http.auth.permission.allow-quarkus-services.policy=permit

quarkus.http.auth.permission.default-deny.paths=/*
quarkus.http.auth.permission.default-deny.policy=deny

quarkus.http.auth.policy.SCL_VALIDATION.roles-allowed=SCL_VALIDATION
quarkus.http.auth.permission.SCL_VALIDATION_POST.paths=/api/v1/validate
quarkus.http.auth.permission.SCL_VALIDATION_POST.policy=SCL_VALIDATION
quarkus.http.auth.permission.SCL_VALIDATION_POST.methods=POST
