quarkus.http.cors.enabled=false

# permit all for local dev
quarkus.http.auth.permission.SCL_VALIDATION_POST.paths=/api/v1/validate
quarkus.http.auth.permission.SCL_VALIDATION_POST.policy=permit-all
quarkus.http.auth.permission.SCL_VALIDATION_POST.methods=POST